### ISSUE TITLE
Improvement: List all channels at once

### ISSUE THREAD

**Issue by joergRossdeutscher** [gitman328/youtube-upload-mail-reminder#3]
I was looking for a way to easily get my channel names & IDs.

Unfortunately I found only one place where youtube lists them all, and that's the sidebar. Even more unfortunately, they are limited by a “More…“ link. And, even more more unfortunately: Since I personally only watch a very limited number of 20 channels I don't know what others see there. And, even MORE unfortunately, the "ABOs“ section does not have a fixed id to find it clean and reliable.

Nevertheless, however, possibly this little hack can help others to find their channels more easy:

1. Go to youtube start page
2. See your channels in the left sidebar under “ABOS“. 
3. The list usually ends with some link like “Show more“. Expand the list with that link until you have a complete list of channels.
4. Open the developer tool of your browser (i.e. Chrome for Mac: Alt-Command-I) and go to the “Console“ tab (Usually it should already open there)
5. CopyPaste this code in one single block:

```
var out="";
document.querySelectorAll('#sections > ytd-guide-section-renderer:nth-child(2) #items a#endpoint[href^="/channel/"]').forEach(function(a){
var channel=a.href.replace(/^.*channel\//uis , '');
var title=a.title;
out+=title+"\t"+channel+"\n";
});
console.log(out);
```
6. Press return

Result like:
```
Acorn To Arabella	UCAiDWnTP0WB1xCp6uuUo0VA
Mister Patina	UCNBN5cN0UHyTsBmY3vs36xQ
Kleines Licht	UC1s67LJmpmW5JxGo3Kx3_iw
my mechanics	UCMrMVIBtqFW6O0-MWq26gqw
Meine Mechaniker	UCkxNIsK8UQsn1VQIL0rWW9w
Harzer Bergbau & Höhlen	UCFWOh0DrZCCd8Hu7_PnppOw
Digital Heritage Service	UC0FuW1N0B7al6yssi7lrkEQ
Helmut Kröner	UC7KCbmGsi4hotZFgvBV0-jw
LADB Restoration	UC8AvcEE8l8mHs-rZTXoynVQ
Restoration Scrap	UCpVKMeHalmhLMlLQ-lUc6vQ
ACME Restorations	UC4WkmPUJFVCKja-Ib9tl-Ow
Mikhandmaker	UCKqedAub4fQCzHhhL5Kxo8w
Alltagskulturen im Rheinland	UCXRNVcpApmIAQhL18i1a3Sw
Steve Cutts	UCpQLC-evmUAon9BBpcW4kYg
rezo	UCLCb_YDL9XfSYsWpS5xrO5Q
Odd Tinkering	UCf_suVrG2dA5BTjJhNLwthQ
Veradona Restoration	UC4DrRcQ8e7I4544juTmgkZg
Landkreis Schaumburg	UC7tXsKL7w1xOk10trFfBsWA
Rescue & Restore	UChzhFNSV-OuHQiYpwDMImsw
Deutsche Fernsehgeschichte	UC2c5naqX8z95-1I2g1a4nQA
```

Disclaimer: I haven't installed far enough to really use that IDs, so everyone feel free to fix this if required.

**Comment by joergRossdeutscher** [comment]
Forgot to add: Feel free to add this to the docs if it works. I herby give up all rights on the code.

**Comment by joergRossdeutscher** [comment]
Idea: When you edit this script a bit, you can directly generate output the SQL commands required to create all channels. Just did this and all my channels now are in the database without requiring to use the web form manually.

Like:
```
INSERT INTO `#channel_list` ( `channel_id`, `channel_name`, `account`, `active`) VALUES ( 'UCMrMVIBtqFW6O0-MWq26gqw', 'my mechanics', '###MY_EMAIL_ADDRESS###, 'yes');
```

**Comment by gitman328** [comment]
Thanks for sharing. I will add this information in readme file. For everyone which want to insert many Channel ID's at once.
