### ISSUE TITLE
Undefined values whan parsing the XML feed

### ISSUE THREAD

**Issue by joergRossdeutscher** [gitman328/youtube-upload-mail-reminder#5]
I have a bad feeling to let the cronjob run with suppressed error reporting and redirected to /dev/null — I think it's best practice to output problems so they can be fixed. So I use the following command to run it

`cd ###MY_PATH_TO_PROJECT### && php -d error_reporting=-1 -f feed_parser.php`

This outputs multiple times repeated:
```
PHP Notice:  Trying to get property 'title' of non-object in ###MY_PATH_TO_PROJECT###/feed_parser.php on line 48
PHP Notice:  Trying to get property 'id' of non-object in ###MY_PATH_TO_PROJECT###/feed_parser.php on line 52
PHP Notice:  Trying to get property 'published' of non-object in ###MY_PATH_TO_PROJECT###/feed_parser.php on line 57
```

I didn't investigate that, however, there is obviously still a flaw in the feed parser.
 
EDIT: Removed critical URLs from posting.

**Comment by gitman328** [comment]
In my opinion that error could only arrives if a channel has lower than 10 videos uploaded.

So some of the ten loop runs into nothing. Try to change the code, to prevent this issue.

Add this line after <code>for ($i = 0; $i <= 9; $i++){</code>

<code>if($feed->entry[$i]->id != ''){</code>

Dont forget to close the if some lines later with bracket }

**Comment by joergRossdeutscher** [comment]
That's the reason, I didn't hink of this…

I suggest a different solution: Limit the processing to the known amount of entries and MAX it to 0-9:

```
if ($feed) {
 $entries = count($feed->entry) - 1;
 if($entries > 9 ){
  $entries = 9;
 }
 for ($i = 0; $i <= $entries; $i++) {
```
