### ISSUE TITLE
Enhancement idea: Get feed list from youtube

### ISSUE THREAD

**Issue by joergRossdeutscher** [gitman328/youtube-upload-mail-reminder#6]
I found this:
http://youtube.com/subscription_manager?action_takeout=1
If you go there with a browser when being logged in, you get a XML feed with all your channels.

While  it is not possible to get this in your app without implementing a login (which will require to setup the whole thing on the youtube API), it might be a good start to let the users get this file from youtube and upload it to your application to create all channels in one easy step.

**Comment by gitman328** [comment]
Great solution.

To implement a textfield where any user could paste the content from his own downloaded subscription_manager.xml would not be so much effort.

Guess this might make more sense than to call the YT API where everyone have to create a token before.

**Comment by gitman328** [comment]
Function was added
